package model;
// Generated 29/04/2021 20:38:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,catalog="persistencia"
)
public class Empleado  implements java.io.Serializable {


     private Integer codEmpleado;
     private String nombres;
     private String apellidos;
     private String sexo;

    public Empleado() {
    }

    public Empleado(String nombres, String apellidos, String sexo) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.sexo = sexo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codEmpleado", unique=true, nullable=false)
    public Integer getCodEmpleado() {
        return this.codEmpleado;
    }
    
    public void setCodEmpleado(Integer codEmpleado) {
        this.codEmpleado = codEmpleado;
    }

    
    @Column(name="nombres", length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


