package model;
// Generated 29/04/2021 20:38:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="persistencia"
)
public class Usuario  implements java.io.Serializable {


     private int codUsuario;
     private String nombre;
     private String clave;

    public Usuario() {
    }

    public Usuario(int codUsuario, String nombre, String clave) {
       this.codUsuario = codUsuario;
       this.nombre = nombre;
       this.clave = clave;
    }
   
     @Id 

    
    @Column(name="codUsuario", unique=true, nullable=false)
    public int getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="clave", nullable=false, length=16)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


